require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/RedundantReturn:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
