require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyle: start_of_line

Layout/ElseAlignment:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
